import { StyleSheet } from 'react-native';
import { Colors, Typography, Spacing, Radius, Shadows } from '../../theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.cream },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.cream,
    gap: Spacing.md,
  },
  loadingText: {
    fontSize: Typography.sizes.xs,
    color: Colors.textMuted,
    fontFamily: Typography.bodyMedium,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },

  header: {
    paddingTop: Spacing.md,
    paddingBottom: Spacing.md + 4,
    paddingHorizontal: Spacing.base,
    alignItems: 'center',
    gap: 4,
  },
  headerTitle: {
    fontFamily: Typography.heading,
    fontSize: 30,
    color: Colors.white,
    letterSpacing: 0.5,
    lineHeight: 34,
  },
  headerOrnamentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    width: '55%',
    marginTop: 2,
  },
  headerOrnamentLine: { flex: 1, height: 1, backgroundColor: 'rgba(212,147,58,0.45)' },
  headerOrnamentGlyph: { fontSize: 8, color: Colors.goldLight },
  headerSub: {
    fontSize: 8,
    letterSpacing: 3,
    color: 'rgba(255,255,255,0.55)',
    fontFamily: Typography.bodyMedium,
  },

  feedContent: {
    padding: Spacing.md,
    gap: Spacing.md,
    paddingBottom: Spacing.xl,
  },

  emptyState: {
    alignItems: 'center',
    paddingTop: Spacing['3xl'],
    paddingHorizontal: Spacing['2xl'],
    gap: Spacing.sm,
  },
  emptyGlyph: { fontSize: 22, color: Colors.gold, marginBottom: 4 },
  emptyTitle: {
    fontFamily: Typography.heading,
    fontSize: Typography.sizes.xl,
    color: Colors.tealDark,
    textAlign: 'center',
    lineHeight: 28,
  },
  emptyText: {
    fontSize: Typography.sizes.sm,
    color: Colors.textMuted,
    fontFamily: Typography.body,
    textAlign: 'center',
    lineHeight: 20,
  },

  feedFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.xl,
  },
  feedFooterLine: { flex: 1, height: 1, backgroundColor: 'rgba(212,147,58,0.18)' },
  feedFooterGlyph: { fontSize: 9, color: Colors.gold },

  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm + 2,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: 'rgba(212,147,58,0.12)',
  },
  inputAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    flexShrink: 0,
  },
  inputAvatarText: {
    fontSize: Typography.sizes.xs,
    fontFamily: Typography.bodySemiBold,
  },
  input: {
    flex: 1,
    backgroundColor: Colors.cream,
    borderRadius: Radius.xl,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm + 2,
    fontSize: Typography.sizes.sm,
    color: Colors.textPrimary,
    fontFamily: Typography.body,
    borderWidth: 1,
    borderColor: 'rgba(212,147,58,0.15)',
    maxHeight: 100,
  },
  sendBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.gold,
  },
  sendBtnText: { fontSize: 14, color: Colors.white },

  modalContainer: { flex: 1, backgroundColor: Colors.cream },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(0,0,0,0.15)',
    alignSelf: 'center',
    marginTop: Spacing.sm,
    marginBottom: 2,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 18,
  },
  modalCloseBtnText: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.85)',
    fontFamily: Typography.bodySemiBold,
  },
  modalTitle: {
    fontFamily: Typography.heading,
    fontSize: Typography.sizes.xl,
    color: Colors.white,
    letterSpacing: 0.3,
  },
  modalHeaderSpacer: { width: 36 },

  originalPostCard: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    margin: Spacing.md,
    marginBottom: 0,
    borderRadius: Radius.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(27,107,107,0.12)',
  },
  originalAccent: { width: 3, backgroundColor: Colors.gold },
  originalInner: { flex: 1, padding: Spacing.sm + 2, gap: 4 },
  originalAuthor: {
    fontFamily: Typography.bodySemiBold,
    fontSize: Typography.sizes.xs,
    color: Colors.teal,
    letterSpacing: 0.2,
  },
  originalContent: {
    fontSize: Typography.sizes.sm,
    color: Colors.textPrimary,
    lineHeight: 20,
    fontFamily: Typography.body,
  },

  modalDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginHorizontal: Spacing.xl,
    marginVertical: Spacing.md,
  },
  modalDividerLine: { flex: 1, height: 1, backgroundColor: 'rgba(212,147,58,0.2)' },
  modalDividerGlyph: { fontSize: 8, color: Colors.gold },

  replyLoading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  repliesList: { paddingHorizontal: Spacing.md, paddingBottom: Spacing.xl, gap: Spacing.md },

  replyEmpty: {
    alignItems: 'center',
    paddingTop: Spacing['2xl'],
    gap: Spacing.sm,
  },
  replyEmptyGlyph: { fontSize: 18, color: 'rgba(212,147,58,0.4)' },
  replyEmptyText: {
    fontSize: Typography.sizes.sm,
    color: Colors.textMuted,
    fontFamily: Typography.body,
  },

  replyInputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm + 2,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: 'rgba(212,147,58,0.12)',
  },
});
