/**
 * GrowthScreen — The Sacred Ledger
 * Daily Growth Tracker: morning intention, personalized tasks, streak.
 * Tasks generated by AI based on user personality type.
 */

import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  View, Text, TouchableOpacity, ScrollView,
  StyleSheet, ActivityIndicator, RefreshControl, Animated,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import {
  doc, getDoc, setDoc, updateDoc,
  serverTimestamp, increment,
} from 'firebase/firestore';
import { db, COLLECTIONS, auth } from '../../services/firebase.client';
import { Colors, Typography, Spacing, Radius, Shadows, Gradients } from '../../theme';
import { useAuthStore } from '../../store/authStore';
import { generateDailyTasks } from '../../services/aiCoach';
import dayjs from 'dayjs';

// ─── Category config ──────────────────────────────────────────────
const TASK_CATEGORIES = {
  spiritual:    { label: 'Spirit',    bg: Colors.tealPale,               text: Colors.teal,   accent: Colors.teal     },
  health:       { label: 'Health',    bg: 'rgba(46,139,87,0.10)',        text: '#2E8B57',     accent: '#2E8B57'       },
  relationship: { label: 'Relation',  bg: Colors.goldPale,               text: Colors.gold,   accent: Colors.gold     },
  mindset:      { label: 'Mindset',   bg: 'rgba(61,124,201,0.10)',       text: '#3D7CC9',     accent: '#3D7CC9'       },
};

function getGreeting() {
  const h = new Date().getHours();
  if (h < 12) return 'Good Morning';
  if (h < 17) return 'Good Afternoon';
  return 'Good Evening';
}

// ─── Animated loading dots ────────────────────────────────────────
function LoadingDots({ color = Colors.teal }) {
  const dots = [
    useRef(new Animated.Value(0)).current,
    useRef(new Animated.Value(0)).current,
    useRef(new Animated.Value(0)).current,
  ];
  useEffect(() => {
    const anims = dots.map((d, i) =>
      Animated.loop(
        Animated.sequence([
          Animated.delay(i * 180),
          Animated.timing(d, { toValue: 1, duration: 380, useNativeDriver: true }),
          Animated.timing(d, { toValue: 0, duration: 380, useNativeDriver: true }),
          Animated.delay((2 - i) * 180),
        ]),
      ),
    );
    anims.forEach(a => a.start());
    return () => anims.forEach(a => a.stop());
  }, []);

  return (
    <View style={ld.row}>
      {dots.map((d, i) => (
        <Animated.View
          key={i}
          style={[
            ld.dot,
            { backgroundColor: color },
            { opacity: d, transform: [{ scale: d.interpolate({ inputRange: [0, 1], outputRange: [0.6, 1.3] }) }] },
          ]}
        />
      ))}
    </View>
  );
}
const ld = StyleSheet.create({
  row: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  dot: { width: 8, height: 8, borderRadius: 4 },
});

// ─── Animated section wrapper ─────────────────────────────────────
function FadeSlide({ anim, delay = 0, children, style }) {
  return (
    <Animated.View
      style={[
        style,
        {
          opacity:   anim,
          transform: [{ translateY: anim.interpolate({ inputRange: [0, 1], outputRange: [20, 0] }) }],
        },
      ]}
    >
      {children}
    </Animated.View>
  );
}

// ─── Ornamental rule ──────────────────────────────────────────────
function OrnamentRule({ label }) {
  return (
    <View style={or.row}>
      <View style={or.line} />
      {label
        ? <Text style={or.label}>{label}</Text>
        : <Text style={or.glyph}>✦</Text>
      }
      <View style={or.line} />
    </View>
  );
}
const or = StyleSheet.create({
  row:   { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  line:  { flex: 1, height: 1, backgroundColor: 'rgba(212,147,58,0.2)' },
  glyph: { fontSize: 9, color: Colors.gold },
  label: { fontSize: 8, color: Colors.textMuted, fontFamily: Typography.bodyMedium, letterSpacing: 2 },
});

// ─── Task check circle with press animation ───────────────────────
function TaskCheck({ done, onPress, accentColor }) {
  const scale = useRef(new Animated.Value(1)).current;

  const handlePress = () => {
    Animated.sequence([
      Animated.timing(scale, { toValue: 0.82, duration: 90, useNativeDriver: true }),
      Animated.spring(scale,  { toValue: 1,    useNativeDriver: true, friction: 4 }),
    ]).start();
    onPress();
  };

  return (
    <TouchableOpacity onPress={handlePress} activeOpacity={1}>
      <Animated.View
        style={[
          tc.circle,
          done
            ? { backgroundColor: accentColor, borderColor: accentColor }
            : { backgroundColor: 'transparent', borderColor: 'rgba(212,147,58,0.35)' },
          { transform: [{ scale }] },
        ]}
      >
        {done && <Text style={tc.check}>✓</Text>}
      </Animated.View>
    </TouchableOpacity>
  );
}
const tc = StyleSheet.create({
  circle: { width: 26, height: 26, borderRadius: 13, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  check:  { fontSize: 12, color: Colors.white, fontFamily: Typography.bodySemiBold },
});

// ─── Main Screen ──────────────────────────────────────────────────
export default function GrowthScreen() {
  const { user, fetchUserProfile } = useAuthStore();
  const [tasks, setTasks]     = useState([]);
  const [motivation, setMot]  = useState('');
  const [loading, setLoading] = useState(true);
  const [generating, setGen]  = useState(false);
  const [refreshing, setRef]  = useState(false);
  const [error, setError]     = useState('');

  const today = dayjs().format('YYYY-MM-DD');

  // Entrance animations — staggered per section
  const anims = useRef([0, 1, 2, 3, 4].map(() => new Animated.Value(0))).current;

  const runEntrance = useCallback(() => {
    Animated.stagger(
      110,
      anims.map(a =>
        Animated.timing(a, { toValue: 1, duration: 520, useNativeDriver: true }),
      ),
    ).start();
  }, []);

  const loadDayData = useCallback(async () => {
    const uid = user?.uid || auth?.currentUser?.uid;
    if (!uid) return;
    setError('');
    try {
      const taskRef  = doc(db, COLLECTIONS.DAILY_TASKS, `${uid}_${today}`);
      const taskSnap = await getDoc(taskRef);
      if (taskSnap.exists()) {
        const data = taskSnap.data();
        setTasks(data.tasks || []);
        setMot(data.motivation || '');
      } else {
        await generateDayPlan(uid);
      }
    } catch (e) {
      console.error('loadDayData:', e);
      setError('Could not load your tasks. Pull down to retry.');
    } finally {
      setLoading(false);
      setRef(false);
    }
  }, [user?.uid, today]);

  useEffect(() => {
    loadDayData();
  }, [loadDayData]);

  useEffect(() => {
    if (!loading) runEntrance();
  }, [loading]);

  // Fallback tasks
  const getFallbackPlan = () => {
    const pType = user?.personalityType || 'The Seeker';
    const motivations = {
      'The Seeker':    'Today, let curiosity be your compass. One question asked in earnest is worth more than a hundred answers given without heart.',
      'The Nurturer':  'Today, give yourself the same kindness you so freely offer others. You cannot pour from an empty vessel.',
      'The Builder':   'Today, take one meaningful step. Not ten steps — one. Done with full intention, it moves mountains.',
      'The Peacemaker':'Today, let your presence be the calm. You don\'t need to fix everything — sometimes just being there is enough.',
    };
    const taskSets = {
      'The Seeker': [
        { id: '1', text: 'Morning prayer with full focus',           category: 'spiritual',    done: false },
        { id: '2', text: 'Study one teaching from the library',      category: 'spiritual',    done: false },
        { id: '3', text: 'Journal: what am I truly seeking today?',  category: 'mindset',      done: false },
        { id: '4', text: '20 min walk — phone away',                 category: 'health',       done: false },
        { id: '5', text: 'Listen fully before responding to someone',category: 'relationship', done: false },
      ],
      'The Nurturer': [
        { id: '1', text: 'Morning prayer with gratitude',            category: 'spiritual',    done: false },
        { id: '2', text: 'Do one thing just for yourself today',     category: 'health',       done: false },
        { id: '3', text: 'Say no to one request if overwhelmed',     category: 'mindset',      done: false },
        { id: '4', text: 'Call or message someone who needs you',    category: 'relationship', done: false },
        { id: '5', text: '15 min stretching or light exercise',      category: 'health',       done: false },
      ],
      'The Builder': [
        { id: '1', text: 'Morning prayer with clear intention',      category: 'spiritual',    done: false },
        { id: '2', text: 'Write down your one goal for today',       category: 'mindset',      done: false },
        { id: '3', text: 'Complete one task without multitasking',   category: 'mindset',      done: false },
        { id: '4', text: '20 min walk or exercise',                  category: 'health',       done: false },
        { id: '5', text: 'Appreciate someone in your life today',    category: 'relationship', done: false },
      ],
      'The Peacemaker': [
        { id: '1', text: 'Morning prayer — sit in silence first',    category: 'spiritual',    done: false },
        { id: '2', text: 'Speak your needs clearly once today',      category: 'mindset',      done: false },
        { id: '3', text: 'Take a slow 15 min walk in nature',        category: 'health',       done: false },
        { id: '4', text: 'Reach out to one person you\'ve avoided',  category: 'relationship', done: false },
        { id: '5', text: 'Read one paragraph of Torah teaching',     category: 'spiritual',    done: false },
      ],
    };
    return {
      tasks:      taskSets[pType] || taskSets['The Seeker'],
      motivation: motivations[pType] || motivations['The Seeker'],
    };
  };

  const generateDayPlan = async (uid) => {
    const resolvedUid = uid || user?.uid || auth?.currentUser?.uid;
    setGen(true);
    let result;
    try {
      result = await generateDailyTasks(user);
    } catch (aiErr) {
      console.warn('AI task generation failed, using fallback:', aiErr.message);
      result = getFallbackPlan();
    } finally {
      setGen(false);
    }
    const docData = {
      userId:      resolvedUid,
      date:        today,
      tasks:       result.tasks,
      motivation:  result.motivation,
      aiGenerated: !result._fallback,
      createdAt:   serverTimestamp(),
    };
    await setDoc(doc(db, COLLECTIONS.DAILY_TASKS, `${resolvedUid}_${today}`), docData);
    setTasks(result.tasks);
    setMot(result.motivation);
  };

  const toggleTask = async (taskId) => {
    const uid = user?.uid || auth?.currentUser?.uid;
    if (!uid) return;
    const previous = tasks;
    const updated  = tasks.map(t => t.id === taskId ? { ...t, done: !t.done } : t);
    setTasks(updated);
    try {
      const ref = doc(db, COLLECTIONS.DAILY_TASKS, `${uid}_${today}`);
      await updateDoc(ref, { tasks: updated });
      const allDone    = updated.every(t => t.done);
      const lastActive = user?.lastActiveDate
        ? dayjs(user.lastActiveDate?.toDate ? user.lastActiveDate.toDate() : user.lastActiveDate).format('YYYY-MM-DD')
        : null;
      if (allDone && lastActive !== today) {
        await updateDoc(doc(db, COLLECTIONS.USERS, uid), {
          streakCount:    increment(1),
          lastActiveDate: serverTimestamp(),
        });
        await fetchUserProfile(uid);
      }
    } catch (e) {
      console.error('toggleTask:', e);
      setTasks(previous);
    }
  };

  const completedCount = tasks.filter(t => t.done).length;
  const totalCount     = tasks.length;
  const progressPct    = totalCount > 0 ? (completedCount / totalCount) * 100 : 0;
  const allDone        = totalCount > 0 && completedCount === totalCount;

  // ── Loading screen ───────────────────────────────────────────────
  if (loading) {
    return (
      <View style={s.loadingContainer}>
        <LoadingDots color={Colors.teal} />
        <Text style={s.loadingTitle}>
          {generating ? 'Preparing your sacred path…' : 'Opening the ledger…'}
        </Text>
        <Text style={s.loadingDate}>{dayjs().format('dddd, MMMM D')}</Text>
      </View>
    );
  }

  // ── Main screen ──────────────────────────────────────────────────
  return (
    <SafeAreaView style={s.container} edges={['top']}>

      {/* ── Header ──────────────────────────────────────────── */}
      <FadeSlide anim={anims[0]}>
        <LinearGradient
          colors={Gradients.teal}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={s.header}
        >
          <Text style={s.headerGreeting}>
            {getGreeting()}, {user?.displayName?.split(' ')[0] || 'Friend'}
          </Text>
          <Text style={s.headerTitle}>Daily Growth</Text>
          <View style={s.headerDivRow}>
            <View style={s.headerDivLine} />
            <Text style={s.headerDivGlyph}>✦</Text>
            <View style={s.headerDivLine} />
          </View>
          <Text style={s.headerDate}>{dayjs().format('dddd, MMMM D')}</Text>
        </LinearGradient>
      </FadeSlide>

      <ScrollView
        style={s.scroll}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={() => { setRef(true); loadDayData(); }}
            tintColor={Colors.teal}
          />
        }
        contentContainerStyle={s.scrollContent}
      >

        {/* ── Error banner ─────────────────────────────────── */}
        {error ? (
          <View style={s.errorBanner}>
            <Text style={s.errorText}>{error}</Text>
          </View>
        ) : null}

        {/* ── Morning intention card ────────────────────────── */}
        {motivation ? (
          <FadeSlide anim={anims[1]}>
            <View style={s.intentionCard}>
              <View style={s.intentionAccent} />
              <View style={s.intentionBody}>
                <View style={s.intentionBadgeRow}>
                  <View style={s.intentionBadge}>
                    <Text style={s.intentionBadgeText}>✦  MORNING INTENTION</Text>
                  </View>
                </View>
                <Text style={s.intentionQuote}>"{motivation}"</Text>
                <Text style={s.intentionSource}>
                  — Tailored for {user?.personalityType || 'your journey'}
                </Text>
              </View>
            </View>
          </FadeSlide>
        ) : null}

        {/* ── Streak medallions ────────────────────────────── */}
        <FadeSlide anim={anims[2]}>
          <OrnamentRule label="YOUR PROGRESS" />
          <View style={s.medallionRow}>

            <View style={s.medallion}>
              <LinearGradient
                colors={[Colors.tealPale, 'rgba(27,107,107,0.05)']}
                style={s.medallionGrad}
              >
                <Text style={s.medallionNum}>{user?.streakCount || 0}</Text>
                <Text style={s.medallionUnit}>days</Text>
                <View style={s.medallionDivider} />
                <Text style={s.medallionLabel}>Streak</Text>
              </LinearGradient>
            </View>

            <View style={[s.medallion, s.medallionCenter]}>
              <LinearGradient
                colors={[Colors.goldPale, 'rgba(212,147,58,0.05)']}
                style={s.medallionGrad}
              >
                <Text style={[s.medallionNum, { color: Colors.gold }]}>{completedCount}</Text>
                <Text style={[s.medallionUnit, { color: Colors.gold }]}>of {totalCount}</Text>
                <View style={[s.medallionDivider, { backgroundColor: 'rgba(212,147,58,0.25)' }]} />
                <Text style={s.medallionLabel}>Done</Text>
              </LinearGradient>
            </View>

            <View style={s.medallion}>
              <LinearGradient
                colors={[Colors.tealPale, 'rgba(27,107,107,0.05)']}
                style={s.medallionGrad}
              >
                <Text style={s.medallionNum}>{Math.round(progressPct)}</Text>
                <Text style={s.medallionUnit}>%</Text>
                <View style={s.medallionDivider} />
                <Text style={s.medallionLabel}>Complete</Text>
              </LinearGradient>
            </View>

          </View>

          {/* Progress bar */}
          <View style={s.progressWrap}>
            <View style={s.progressBg}>
              <LinearGradient
                colors={allDone ? [Colors.gold, Colors.goldLight] : [Colors.teal, Colors.tealLight || '#2A8A8A']}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 0 }}
                style={[s.progressFill, { width: `${progressPct}%` }]}
              />
            </View>
          </View>

          {allDone && (
            <View style={s.allDoneBanner}>
              <Text style={s.allDoneGlyph}>✦</Text>
              <Text style={s.allDoneText}>All complete — a blessed day's work!</Text>
              <Text style={s.allDoneGlyph}>✦</Text>
            </View>
          )}
        </FadeSlide>

        {/* ── Task list ────────────────────────────────────── */}
        <FadeSlide anim={anims[3]}>
          <OrnamentRule label="TODAY'S TASKS" />
          <View style={s.taskList}>
            {tasks.map((task, idx) => {
              const cat = TASK_CATEGORIES[task.category] || TASK_CATEGORIES.spiritual;
              return (
                <View
                  key={task.id}
                  style={[
                    s.taskCard,
                    task.done && s.taskCardDone,
                    { borderLeftColor: task.done ? cat.accent : 'rgba(212,147,58,0.18)' },
                  ]}
                >
                  <TaskCheck
                    done={task.done}
                    onPress={() => toggleTask(task.id)}
                    accentColor={cat.accent}
                  />

                  <View style={s.taskBody}>
                    <Text
                      style={[s.taskText, task.done && s.taskTextDone]}
                      numberOfLines={2}
                    >
                      {task.text}
                    </Text>
                  </View>

                  <View style={[s.catPill, { backgroundColor: cat.bg }]}>
                    <Text style={[s.catPillText, { color: cat.text }]}>{cat.label}</Text>
                  </View>
                </View>
              );
            })}
          </View>
        </FadeSlide>

        {/* ── Personality nature card ───────────────────────── */}
        {user?.personalityType && (
          <FadeSlide anim={anims[4]}>
            <OrnamentRule />
            <View style={s.natureCard}>
              <View style={s.natureCardTop}>
                <Text style={s.natureCardEyebrow}>YOUR NATURE</Text>
                <Text style={s.natureCardType}>{user.personalityType}</Text>
              </View>
              {(user.mbtiType || user.enneagramType) && (
                <View style={s.natureCardMeta}>
                  {user.mbtiType     && <View style={s.naturePill}><Text style={s.naturePillText}>{user.mbtiType}</Text></View>}
                  {user.enneagramType && <View style={s.naturePill}><Text style={s.naturePillText}>{user.enneagramType}</Text></View>}
                </View>
              )}
            </View>
          </FadeSlide>
        )}

        {/* Bottom padding */}
        <View style={{ height: Spacing['2xl'] }} />
      </ScrollView>
    </SafeAreaView>
  );
}

// ─── Styles ───────────────────────────────────────────────────────
const s = StyleSheet.create({
  container:      { flex: 1, backgroundColor: Colors.cream },
  loadingContainer: {
    flex: 1, alignItems: 'center', justifyContent: 'center',
    backgroundColor: Colors.cream, gap: Spacing.md,
  },
  loadingTitle: {
    fontFamily: Typography.heading,
    fontSize: Typography.sizes.xl,
    color: Colors.tealDark,
    textAlign: 'center',
    marginTop: 2,
  },
  loadingDate: {
    fontSize: Typography.sizes.xs,
    color: Colors.textMuted,
    fontFamily: Typography.body,
    letterSpacing: 0.5,
  },

  // ── Header ──────────────────────────────────────────────────────
  header: {
    paddingHorizontal: Spacing.base,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.lg + 2,
    alignItems: 'center',
    gap: 3,
  },
  headerGreeting: {
    fontSize: 9,
    letterSpacing: 2.5,
    color: 'rgba(255,255,255,0.65)',
    fontFamily: Typography.bodyMedium,
    textTransform: 'uppercase',
  },
  headerTitle: {
    fontFamily: Typography.heading,
    fontSize: 34,
    color: Colors.white,
    letterSpacing: 0.5,
    lineHeight: 38,
  },
  headerDivRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    width: '52%',
    marginTop: 2,
  },
  headerDivLine:  { flex: 1, height: 1, backgroundColor: 'rgba(212,147,58,0.4)' },
  headerDivGlyph: { fontSize: 8, color: Colors.goldLight },
  headerDate: {
    fontSize: Typography.sizes.xs,
    color: 'rgba(255,255,255,0.55)',
    fontFamily: Typography.body,
    letterSpacing: 0.3,
  },

  // ── Scroll ───────────────────────────────────────────────────────
  scroll:        { flex: 1 },
  scrollContent: { paddingHorizontal: Spacing.base, paddingTop: Spacing.md, gap: Spacing.md, paddingBottom: Spacing.xl },

  // ── Error ─────────────────────────────────────────────────────────
  errorBanner: {
    backgroundColor: 'rgba(220,53,69,0.08)',
    borderRadius: Radius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(220,53,69,0.25)',
  },
  errorText: { fontSize: Typography.sizes.sm, color: '#DC3545', fontFamily: Typography.body, textAlign: 'center' },

  // ── Morning intention ────────────────────────────────────────────
  intentionCard: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(212,147,58,0.15)',
    ...Shadows.sm,
  },
  intentionAccent: { width: 3.5, backgroundColor: Colors.gold },
  intentionBody:   { flex: 1, padding: Spacing.md, gap: 8 },
  intentionBadgeRow: { flexDirection: 'row' },
  intentionBadge: {
    backgroundColor: Colors.goldPale,
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: Radius.sm,
    alignSelf: 'flex-start',
  },
  intentionBadgeText: {
    fontSize: 8,
    color: Colors.gold,
    fontFamily: Typography.bodySemiBold,
    letterSpacing: 1.5,
  },
  intentionQuote: {
    fontFamily: Typography.body,
    fontSize: Typography.sizes.sm,
    color: Colors.textPrimary,
    lineHeight: 22,
    fontStyle: 'italic',
  },
  intentionSource: {
    fontSize: Typography.sizes.xs,
    color: Colors.teal,
    fontFamily: Typography.bodySemiBold,
    letterSpacing: 0.2,
  },

  // ── Medallions ───────────────────────────────────────────────────
  medallionRow:   { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.sm },
  medallion:      { flex: 1, borderRadius: Radius.lg, overflow: 'hidden', borderWidth: 1, borderColor: 'rgba(27,107,107,0.12)', ...Shadows.sm },
  medallionCenter:{ borderColor: 'rgba(212,147,58,0.2)' },
  medallionGrad:  { alignItems: 'center', paddingVertical: Spacing.md + 2, gap: 2 },
  medallionNum: {
    fontFamily: Typography.heading,
    fontSize: 36,
    color: Colors.teal,
    lineHeight: 38,
  },
  medallionUnit: {
    fontSize: 9,
    color: Colors.teal,
    fontFamily: Typography.bodyMedium,
    letterSpacing: 0.5,
    opacity: 0.75,
  },
  medallionDivider: { width: 20, height: 1, backgroundColor: 'rgba(27,107,107,0.2)', marginVertical: 4 },
  medallionLabel: {
    fontSize: 8,
    color: Colors.textMuted,
    fontFamily: Typography.bodyMedium,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },

  // Progress bar
  progressWrap: { marginTop: Spacing.sm },
  progressBg: {
    height: 7,
    backgroundColor: 'rgba(27,107,107,0.1)',
    borderRadius: Radius.full,
    overflow: 'hidden',
  },
  progressFill: { height: '100%', borderRadius: Radius.full },

  // All done banner
  allDoneBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  allDoneGlyph: { fontSize: 10, color: Colors.gold },
  allDoneText: {
    fontSize: Typography.sizes.xs,
    color: Colors.gold,
    fontFamily: Typography.bodyMedium,
    letterSpacing: 0.5,
  },

  // ── Task list ────────────────────────────────────────────────────
  taskList: { gap: Spacing.sm, marginTop: Spacing.sm },
  taskCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    backgroundColor: Colors.white,
    borderRadius: Radius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(212,147,58,0.12)',
    borderLeftWidth: 3,
    borderLeftColor: 'rgba(212,147,58,0.18)',
    ...Shadows.sm,
  },
  taskCardDone: {
    backgroundColor: 'rgba(245,239,230,0.6)',
    borderColor: 'rgba(27,107,107,0.08)',
  },
  taskBody:     { flex: 1 },
  taskText: {
    fontSize: Typography.sizes.sm,
    color: Colors.textPrimary,
    fontFamily: Typography.body,
    lineHeight: 20,
  },
  taskTextDone: {
    color: Colors.textMuted,
    textDecorationLine: 'line-through',
  },
  catPill: {
    borderRadius: Radius.sm,
    paddingVertical: 3,
    paddingHorizontal: 8,
    flexShrink: 0,
  },
  catPillText: {
    fontSize: 8,
    fontFamily: Typography.bodySemiBold,
    letterSpacing: 0.5,
  },

  // ── Nature card ──────────────────────────────────────────────────
  natureCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(212,147,58,0.18)',
    marginTop: Spacing.sm,
    ...Shadows.sm,
  },
  natureCardTop: {
    alignItems: 'center',
    paddingVertical: Spacing.md + 2,
    paddingHorizontal: Spacing.base,
    gap: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(212,147,58,0.1)',
  },
  natureCardEyebrow: {
    fontSize: 8,
    letterSpacing: 2.5,
    color: Colors.gold,
    fontFamily: Typography.bodyMedium,
    textTransform: 'uppercase',
  },
  natureCardType: {
    fontFamily: Typography.heading,
    fontSize: Typography.sizes['2xl'],
    color: Colors.tealDark,
    letterSpacing: 0.3,
  },
  natureCardMeta: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.sm + 2,
    paddingHorizontal: Spacing.base,
  },
  naturePill: {
    backgroundColor: Colors.tealPale,
    borderRadius: Radius.sm,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(27,107,107,0.15)',
  },
  naturePillText: {
    fontSize: Typography.sizes.xs,
    color: Colors.teal,
    fontFamily: Typography.bodySemiBold,
    letterSpacing: 0.3,
  },
});
