/**
 * GrowthScreen — Daily Growth Tracker
 * Morning motivation, personalized daily tasks, streak tracking.
 * Tasks generated by AI based on user personality type.
 */

import React, { useState, useEffect, useCallback } from 'react';
import {
  View, Text, TouchableOpacity, ScrollView,
  StyleSheet, ActivityIndicator, RefreshControl,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import {
  doc, getDoc, setDoc, updateDoc,
  collection, query, where, orderBy, getDocs,
  serverTimestamp,
} from 'firebase/firestore';
import { db, COLLECTIONS } from '../../services/firebase.client';
import { Colors, Typography, Spacing, Radius, Shadows, Gradients } from '../../theme';
import { useAuthStore } from '../../store/authStore';
import dayjs from 'dayjs';

const TASK_CATEGORIES = {
  spiritual:   { label: 'Spirit',    bg: Colors.tealPale,                        text: Colors.teal },
  health:      { label: 'Health',    bg: 'rgba(76,175,130,0.12)',                 text: '#2E8B57' },
  relationship:{ label: 'Relation',  bg: Colors.goldPale,                         text: Colors.gold },
  mindset:     { label: 'Mindset',   bg: 'rgba(61,124,201,0.12)',                 text: '#3D7CC9' },
};

const GREETING = () => {
  const h = new Date().getHours();
  if (h < 12) return 'Good Morning';
  if (h < 17) return 'Good Afternoon';
  return 'Good Evening';
};

export default function GrowthScreen() {
  const { user }              = useAuthStore();
  const [tasks, setTasks]     = useState([]);
  const [motivation, setMot]  = useState('');
  const [loading, setLoading] = useState(true);
  const [refreshing, setRef]  = useState(false);

  const today = dayjs().format('YYYY-MM-DD');

  const loadDayData = useCallback(async () => {
    if (!user) return;
    try {
      // Load today's tasks
      const taskRef  = doc(db, COLLECTIONS.DAILY_TASKS, `${user.uid}_${today}`);
      const taskSnap = await getDoc(taskRef);

      if (taskSnap.exists()) {
        const data = taskSnap.data();
        setTasks(data.tasks || []);
        setMot(data.motivation || '');
      } else {
        // Generate new tasks for today via AI
        await generateDayPlan();
      }
    } catch (e) {
      console.error('loadDayData:', e);
    } finally {
      setLoading(false);
      setRef(false);
    }
  }, [user, today]);

  useEffect(() => { loadDayData(); }, [loadDayData]);

  // Generate daily plan — calls AI via backend function
  const generateDayPlan = async () => {
    // In production: call a Firebase Cloud Function that calls OpenAI
    // and generates personalized tasks + motivation based on user.personalityType
    // For now, using defaults based on personality type
    const defaultMotivations = {
      'The Seeker':    'Today, let curiosity be your compass. One question asked in earnest is worth more than a hundred answers given without heart.',
      'The Nurturer':  'Today, give yourself the same kindness you so freely offer others. You cannot pour from an empty vessel.',
      'The Builder':   'Today, take one meaningful step. Not ten steps — one. Done with full intention, it moves mountains.',
      'The Peacemaker':'Today, let your presence be the calm. You don\'t need to fix everything — sometimes just being there is enough.',
    };

    const defaultTasks = {
      'The Seeker': [
        { id: '1', text: 'Morning prayer with full focus',           category: 'spiritual',    done: false },
        { id: '2', text: 'Study one teaching from the library',      category: 'spiritual',    done: false },
        { id: '3', text: 'Journal: what am I truly seeking today?',  category: 'mindset',      done: false },
        { id: '4', text: '20 min walk — phone away',                 category: 'health',       done: false },
        { id: '5', text: 'Listen fully before responding to spouse', category: 'relationship', done: false },
      ],
      'The Nurturer': [
        { id: '1', text: 'Morning prayer with gratitude',            category: 'spiritual',    done: false },
        { id: '2', text: 'Do one thing just for yourself today',     category: 'health',       done: false },
        { id: '3', text: 'Say no to one request if overwhelmed',     category: 'mindset',      done: false },
        { id: '4', text: 'Call or message someone who needs you',    category: 'relationship', done: false },
        { id: '5', text: '15 min stretching or light exercise',      category: 'health',       done: false },
      ],
    };

    const pType      = user?.personalityType || 'The Seeker';
    const tasks      = defaultTasks[pType] || defaultTasks['The Seeker'];
    const motivation = defaultMotivations[pType] || defaultMotivations['The Seeker'];

    const docData = {
      userId:     user.uid,
      date:       today,
      tasks,
      motivation,
      createdAt:  serverTimestamp(),
    };

    await setDoc(doc(db, COLLECTIONS.DAILY_TASKS, `${user.uid}_${today}`), docData);
    setTasks(tasks);
    setMot(motivation);
  };

  const toggleTask = async (taskId) => {
    const updated = tasks.map(t =>
      t.id === taskId ? { ...t, done: !t.done } : t
    );
    setTasks(updated);
    const ref = doc(db, COLLECTIONS.DAILY_TASKS, `${user.uid}_${today}`);
    await updateDoc(ref, { tasks: updated });

    // Update streak if all tasks done
    const allDone = updated.every(t => t.done);
    if (allDone) {
      await updateDoc(doc(db, COLLECTIONS.USERS, user.uid), {
        streakCount:    (user.streakCount || 0) + 1,
        lastActiveDate: serverTimestamp(),
      });
    }
  };

  const completedCount = tasks.filter(t => t.done).length;
  const totalCount     = tasks.length;
  const progressPct    = totalCount > 0 ? (completedCount / totalCount) * 100 : 0;

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color={Colors.teal} />
      </View>
    );
  }

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      {/* Header */}
      <LinearGradient colors={Gradients.teal} style={styles.header}>
        <Text style={styles.headerGreeting}>{GREETING()}, {user?.displayName?.split(' ')[0] || 'Friend'} 🔥</Text>
        <Text style={styles.headerTitle}>Your Daily Growth</Text>
        <Text style={styles.headerDate}>{dayjs().format('dddd, MMMM D')}</Text>
      </LinearGradient>

      <ScrollView
        style={styles.scroll}
        showsVerticalScrollIndicator={false}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRef(true); loadDayData(); }} tintColor={Colors.teal} />}
        contentContainerStyle={styles.scrollContent}
      >
        {/* Morning motivation */}
        {motivation ? (
          <View style={styles.motivationCard}>
            <LinearGradient colors={Gradients.teal} style={styles.motivationGradient}>
              <Text style={styles.motivationLabel}>✦  MORNING INTENTION</Text>
              <Text style={styles.motivationText}>"{motivation}"</Text>
              <Text style={styles.motivationSource}>
                — Tailored for {user?.personalityType || 'your journey'}
              </Text>
            </LinearGradient>
          </View>
        ) : null}

        {/* Streak cards */}
        <View style={styles.streakRow}>
          <View style={styles.streakCard}>
            <Text style={styles.streakNum}>{user?.streakCount || 0}</Text>
            <Text style={styles.streakLabel}>Day Streak</Text>
          </View>
          <View style={styles.streakCard}>
            <Text style={styles.streakNum}>{totalCount}</Text>
            <Text style={styles.streakLabel}>Tasks Today</Text>
          </View>
          <View style={styles.streakCard}>
            <Text style={styles.streakNum}>{completedCount}</Text>
            <Text style={styles.streakLabel}>Completed</Text>
          </View>
        </View>

        {/* Progress bar */}
        <View style={styles.progressSection}>
          <View style={styles.progressHeader}>
            <Text style={styles.progressLabel}>Today's Progress</Text>
            <Text style={styles.progressPct}>{Math.round(progressPct)}%</Text>
          </View>
          <View style={styles.progressBg}>
            <View style={[styles.progressFill, { width: `${progressPct}%` }]} />
          </View>
          {completedCount === totalCount && totalCount > 0 && (
            <Text style={styles.allDoneText}>🎉 All tasks complete! Amazing work today.</Text>
          )}
        </View>

        {/* Task list */}
        <View style={styles.tasksSection}>
          <Text style={styles.sectionTitle}>Today's Tasks</Text>
          {tasks.map(task => {
            const cat = TASK_CATEGORIES[task.category] || TASK_CATEGORIES.spiritual;
            return (
              <TouchableOpacity
                key={task.id}
                style={styles.taskItem}
                onPress={() => toggleTask(task.id)}
                activeOpacity={0.7}
              >
                <View style={[styles.taskCheck, task.done && styles.taskCheckDone]}>
                  {task.done && <Text style={styles.taskCheckIcon}>✓</Text>}
                </View>
                <Text style={[styles.taskText, task.done && styles.taskTextDone]} numberOfLines={2}>
                  {task.text}
                </Text>
                <View style={[styles.catBadge, { backgroundColor: cat.bg }]}>
                  <Text style={[styles.catBadgeText, { color: cat.text }]}>{cat.label}</Text>
                </View>
              </TouchableOpacity>
            );
          })}
        </View>

        {/* Personality type reminder */}
        {user?.personalityType && (
          <View style={styles.typeCard}>
            <Text style={styles.typeCardLabel}>Your Nature</Text>
            <Text style={styles.typeCardType}>{user.personalityType}</Text>
            {user.mbtiType && <Text style={styles.typeCardSub}>{user.mbtiType} · {user.enneagramType}</Text>}
          </View>
        )}

        <View style={{ height: Spacing.xl }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.cream },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.cream },

  header: { paddingHorizontal: Spacing.base, paddingVertical: Spacing.base, paddingBottom: Spacing.lg },
  headerGreeting: { fontSize: Typography.sizes.xs, color: Colors.goldLight, marginBottom: 2 },
  headerTitle:    { fontFamily: Typography.heading, fontSize: Typography.sizes['2xl'], color: Colors.white, fontWeight: '700' },
  headerDate:     { fontSize: Typography.sizes.xs, color: 'rgba(255,255,255,0.6)', marginTop: 3 },

  scroll: { flex: 1 },
  scrollContent: { padding: Spacing.base, gap: Spacing.md },

  motivationCard: { borderRadius: Radius.lg, overflow: 'hidden', ...Shadows.md },
  motivationGradient: { padding: Spacing.base },
  motivationLabel: { fontSize: Typography.sizes.xs, color: Colors.goldLight, letterSpacing: 1, textTransform: 'uppercase', fontFamily: Typography.bodySemiBold, marginBottom: Spacing.sm },
  motivationText:  { fontSize: Typography.sizes.sm, color: 'rgba(255,255,255,0.92)', lineHeight: 20, fontStyle: 'italic', fontFamily: Typography.body },
  motivationSource:{ fontSize: Typography.sizes.xs, color: Colors.goldLight, marginTop: Spacing.sm },

  streakRow: { flexDirection: 'row', gap: Spacing.sm },
  streakCard: {
    flex: 1, backgroundColor: Colors.white, borderRadius: Radius.lg,
    padding: Spacing.md, alignItems: 'center', borderWidth: 1,
    borderColor: Colors.borderLight, ...Shadows.sm,
  },
  streakNum:   { fontFamily: Typography.heading, fontSize: Typography.sizes['3xl'], color: Colors.teal },
  streakLabel: { fontSize: Typography.sizes.xs, color: Colors.textMuted, marginTop: 2, fontFamily: Typography.body },

  progressSection: { gap: Spacing.xs },
  progressHeader:  { flexDirection: 'row', justifyContent: 'space-between' },
  progressLabel:   { fontSize: Typography.sizes.sm, color: Colors.textPrimary, fontFamily: Typography.bodyMedium },
  progressPct:     { fontSize: Typography.sizes.sm, color: Colors.teal, fontFamily: Typography.bodySemiBold },
  progressBg:      { height: 8, backgroundColor: Colors.creamDark, borderRadius: Radius.full, overflow: 'hidden' },
  progressFill:    { height: '100%', backgroundColor: Colors.teal, borderRadius: Radius.full },
  allDoneText:     { fontSize: Typography.sizes.xs, color: Colors.success, fontFamily: Typography.body },

  tasksSection: { gap: Spacing.sm },
  sectionTitle: { fontSize: Typography.sizes.xs, color: Colors.tealDark, textTransform: 'uppercase', letterSpacing: 1, fontFamily: Typography.bodySemiBold },
  taskItem: {
    flexDirection: 'row', alignItems: 'center', gap: Spacing.md,
    backgroundColor: Colors.white, borderRadius: Radius.md, padding: Spacing.md,
    borderWidth: 1, borderColor: Colors.borderLight, ...Shadows.sm,
  },
  taskCheck: {
    width: 22, height: 22, borderRadius: 11,
    borderWidth: 2, borderColor: Colors.border,
    alignItems: 'center', justifyContent: 'center', flexShrink: 0,
  },
  taskCheckDone:  { backgroundColor: Colors.success, borderColor: Colors.success },
  taskCheckIcon:  { fontSize: 11, color: Colors.white, fontFamily: Typography.bodySemiBold },
  taskText:       { flex: 1, fontSize: Typography.sizes.sm, color: Colors.textPrimary, fontFamily: Typography.body, lineHeight: 18 },
  taskTextDone:   { color: Colors.textMuted, textDecorationLine: 'line-through' },
  catBadge:       { borderRadius: Radius.sm, paddingHorizontal: Spacing.xs, paddingVertical: 2, flexShrink: 0 },
  catBadgeText:   { fontSize: 9, fontFamily: Typography.bodySemiBold },

  typeCard: {
    backgroundColor: Colors.tealPale, borderRadius: Radius.lg,
    padding: Spacing.base, borderWidth: 1, borderColor: Colors.border,
    alignItems: 'center',
  },
  typeCardLabel: { fontSize: Typography.sizes.xs, color: Colors.teal, textTransform: 'uppercase', letterSpacing: 1, fontFamily: Typography.bodySemiBold },
  typeCardType:  { fontFamily: Typography.heading, fontSize: Typography.sizes.xl, color: Colors.tealDark, marginTop: 2 },
  typeCardSub:   { fontSize: Typography.sizes.xs, color: Colors.textMuted, marginTop: 2, fontFamily: Typography.body },
});
