import { StyleSheet } from 'react-native';
import { Colors, Typography, Spacing, Radius, Shadows } from '../../theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.cream },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.cream },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  backBtn: { width: 34, alignItems: 'center', justifyContent: 'center' },
  backBtnText: { fontSize: Typography.sizes.xl, color: Colors.teal },
  headerTitle: { fontFamily: Typography.heading, fontSize: Typography.sizes.xl, color: Colors.tealDark },
  headerSpacer: { width: 34 },

  offlineGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing['2xl'],
    gap: Spacing.base,
  },
  offlineIcon: { fontSize: 56 },
  offlineTitle: {
    fontFamily: Typography.heading,
    fontSize: Typography.sizes['2xl'],
    color: Colors.white,
    textAlign: 'center',
  },
  offlineSub: {
    fontSize: Typography.sizes.md,
    color: 'rgba(255,255,255,0.75)',
    textAlign: 'center',
    lineHeight: 22,
    fontFamily: Typography.body,
  },
  offlineNote: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginTop: Spacing.md,
  },
  offlineNoteText: { fontSize: Typography.sizes.sm, color: 'rgba(255,255,255,0.8)', fontFamily: Typography.body },

  inviteGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing['2xl'],
    gap: Spacing.lg,
  },
  inviteIcon: { fontSize: 64 },
  inviteTitle: {
    fontFamily: Typography.heading,
    fontSize: Typography.sizes['3xl'],
    color: Colors.white,
    textAlign: 'center',
  },
  inviteSub: {
    fontSize: Typography.sizes.md,
    color: 'rgba(255,255,255,0.85)',
    textAlign: 'center',
    lineHeight: 24,
    fontFamily: Typography.body,
  },
  joinConsultBtn: {
    backgroundColor: Colors.white,
    borderRadius: Radius.xl,
    paddingHorizontal: Spacing['2xl'],
    paddingVertical: Spacing.base,
    marginTop: Spacing.md,
    ...Shadows.gold,
  },
  joinConsultBtnText: { fontFamily: Typography.bodySemiBold, fontSize: Typography.sizes.base, color: Colors.gold },
  declineBtn: { paddingVertical: Spacing.sm },
  declineBtnText: { fontSize: Typography.sizes.sm, color: 'rgba(255,255,255,0.6)', fontFamily: Typography.body },

  consultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.base,
    paddingVertical: Spacing.md,
  },
  consultHeaderLabel: { fontFamily: Typography.bodySemiBold, fontSize: Typography.sizes.md, color: Colors.white },
  consultTimerBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.md,
    paddingVertical: 4,
  },
  consultTimerUrgent: { backgroundColor: Colors.error },
  consultTimerText: { fontFamily: Typography.bodySemiBold, fontSize: Typography.sizes.base, color: Colors.white },
  consultRemoteWrap: { flex: 1, backgroundColor: '#000', position: 'relative' },
  localPip: {
    position: 'absolute',
    bottom: 100,
    right: Spacing.base,
    width: 90,
    height: 130,
    borderRadius: Radius.md,
    backgroundColor: Colors.tealDark,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: Colors.white,
    zIndex: 10,
    elevation: 10,
  },
  waitingVideoText: {
    color: 'rgba(255,255,255,0.5)',
    fontFamily: Typography.body,
    fontSize: Typography.sizes.sm,
    marginTop: Spacing.md,
  },
  consultFooter: { padding: Spacing.base, backgroundColor: Colors.white },
  endConsultBtn: { backgroundColor: Colors.error, borderRadius: Radius.xl, padding: Spacing.md, alignItems: 'center' },
  endConsultBtnText: { fontFamily: Typography.bodySemiBold, fontSize: Typography.sizes.md, color: Colors.white },

  liveHeader: { padding: Spacing.base, paddingBottom: Spacing.md },
  liveHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  livePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: 'rgba(224,92,92,0.2)',
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
  },
  liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: Colors.error },
  liveText: { fontSize: 10, color: '#FF8888', fontFamily: Typography.bodySemiBold, letterSpacing: 1 },
  watchingCount: { fontSize: Typography.sizes.xs, color: 'rgba(255,255,255,0.65)', fontFamily: Typography.body },
  liveTitle: { fontFamily: Typography.heading, fontSize: Typography.sizes.xl, color: Colors.white },
  liveSubtitle: { fontSize: Typography.sizes.xs, color: Colors.goldLight, marginTop: 2, fontFamily: Typography.body },

  videoArea: { height: 220, backgroundColor: '#000', position: 'relative' },
  videoOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0A1A1A',
    gap: Spacing.md,
    zIndex: 1,
  },
  videoErrorIcon: { fontSize: 36 },
  videoOverlayText: { fontSize: Typography.sizes.sm, color: 'rgba(255,255,255,0.5)', fontFamily: Typography.body },
  videoOverlaySubText: { fontSize: Typography.sizes.xs, color: 'rgba(255,255,255,0.35)', fontFamily: Typography.body },
  videoTimer: {
    position: 'absolute',
    bottom: Spacing.sm,
    right: Spacing.sm,
    backgroundColor: 'rgba(0,0,0,0.65)',
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    zIndex: 2,
  },
  videoTimerText: { fontSize: Typography.sizes.xs, color: Colors.white, fontFamily: Typography.bodyMedium },

  waitingSection: { flex: 1, padding: Spacing.md, gap: Spacing.sm },
  waitingHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  waitingTitle: {
    fontFamily: Typography.bodySemiBold,
    fontSize: Typography.sizes.sm,
    color: Colors.tealDark,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  waitingCount: { fontSize: Typography.sizes.xs, color: Colors.textMuted, fontFamily: Typography.body },

  myPositionCard: { borderRadius: Radius.lg, padding: Spacing.md, alignItems: 'center' },
  myPositionLabel: {
    fontSize: Typography.sizes.xs,
    color: Colors.goldLight,
    letterSpacing: 1,
    fontFamily: Typography.bodySemiBold,
  },
  myPositionNum: { fontFamily: Typography.heading, fontSize: 40, color: Colors.white },
  myPositionWait: { fontSize: Typography.sizes.xs, color: 'rgba(255,255,255,0.7)', fontFamily: Typography.body },

  queueList: { flex: 1 },
  queueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    backgroundColor: Colors.white,
    borderRadius: Radius.md,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    marginBottom: Spacing.xs,
  },
  queueItemMe: { borderColor: Colors.teal, borderWidth: 2, backgroundColor: Colors.tealPale },
  queueNum: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  queueNumDefault: { backgroundColor: Colors.creamDark },
  queueNumFirst: { backgroundColor: Colors.success },
  queueNumMe: { backgroundColor: Colors.teal },
  queueNumText: { fontSize: Typography.sizes.xs, color: Colors.textMuted, fontFamily: Typography.bodySemiBold },
  queueName: { flex: 1, fontSize: Typography.sizes.sm, color: Colors.textPrimary, fontFamily: Typography.body },
  queueNameMe: { color: Colors.tealDark, fontFamily: Typography.bodySemiBold },
  inSessionBadge: { fontSize: Typography.sizes.xs, color: Colors.success, fontFamily: Typography.bodySemiBold },
  youBadge: { fontSize: Typography.sizes.xs, color: Colors.teal, fontFamily: Typography.bodySemiBold },

  joinBtn: { backgroundColor: Colors.gold, borderRadius: Radius.xl, padding: Spacing.base, alignItems: 'center', ...Shadows.gold },
  joinBtnDisabled: { opacity: 0.6 },
  joinBtnText: { fontFamily: Typography.bodySemiBold, fontSize: Typography.sizes.md, color: Colors.white },
  leaveBtn: {
    borderWidth: 1,
    borderColor: 'rgba(224,92,92,0.3)',
    borderRadius: Radius.xl,
    padding: Spacing.md,
    alignItems: 'center',
  },
  leaveBtnText: { fontSize: Typography.sizes.sm, color: Colors.error, fontFamily: Typography.bodyMedium },
});
